apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: cc9oj2ovg-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/cc9oj2ovg-java-quarkus-gitops