apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: cc9oj2ovg-java-quarkus
  janus-idp.io/tekton: cc9oj2ovg-java-quarkus
  backstage.io/kubernetes-id: cc9oj2ovg-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cc9oj2ovg-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
